# yaml-language-server: $schema=../schemas/agent.config.schema.json

llm:
  api_url: https://api.openai.com/v1
  api_key: "${A3S_LLM_API_KEY}"
  model: gpt-4o-mini

agent:
  name: Cody
  description: A helpful coding assistant
  instructions: |
    You are a coding agent. Use the tools provided to access the user's requests
    regarding coding tasks.

server:
  listen_address: 127.0.0.1
  listen_port: 8000

mcp_servers:
  - url: http://mcp1.example.com/mcp
    auth: none
  - url: http://mcp2.example.com/mcp
    auth:
      mode: oauth_client_credentials
      token_endpoint: http://mcp2.example.com/mcp/token
      client_id: myclient
      client_secret: ${A3S_MCP2_CLIENT_SECRET}
      auth_method: client_secret_post # Defaults to client_secret_basic.

  # `oauth_token_exchange` and `oauth_token_forward` modes require that the
  # root-level `auth.mode` be `oauth2`, since they expect a token to be
  # provided
  # - url: http://mcp3.example.com/mcp
  #   auth:
  #     mode: oauth_token_forward
  # - url: http://mcp4.example.com/mcp
  #   auth:
  #     mode: oauth_token_exchange
  #
  #     discovered: true # Discovered from the metadata of the authorization
  #                      # server (defined at `auth.issuer_url`)
  #     # Or configure the endpoint directly instead:
  #     discovered: false
  #     token_endpoint: http://mcp4.example.com/mcp/token
  #
  #     client_id: myclient
  #     client_secret: ${A3S_MCP4_CLIENT_SECRET}
  #     auth_method: client_secret_post # Defaults to client_secret_basic.

auth: none
# auth:
#   mode: api_key
#   api_key: ${A3S_AGENT_API_KEY}
# auth:
#   mode: oauth2
#   issuer_url: http://auth.example.com
#   policies:
#     jwt:
#       jwks:
#         discovered: true
#         # Or use an explicit JWKS endpoint instead:
#         discovered: false
#         url: http://auth.example.com/.well-known/jwks.json
#
#       # Enable RFC 9068 claims validation
#       rfc9068:
#         resource_server: my_resource_server_identifier
#
#       claims:
#         scope: read
#
#     # Enable token introspection
#     introspection:
#       discovered: true
#       # Or configure the endpoint directly instead:
#       discovered: false
#       endpoint: http://auth.example.com/oauth/introspect
#
#       client_id: ${A3S_AGENT_INTROSPECTION_CLIENT_ID}
#       client_secret: ${A3S_AGENT_INTROSPECTION_CLIENT_SECRET}
#
#       # Defaults to client_secret_basic.
#       auth_method: client_secret_post

logging:
  level: "INFO"
  format: "plain"
