import json
from pathlib import Path
from typing import Any

from src.config.config import Config

SCHEMA_PATH = (
    Path(__file__).resolve().parents[3] / "schemas" / "agent.config.schema.json"
)
ENV_VAR_PLACEHOLDER_REF = "#/$defs/EnvVarPlaceholder"


def strip_env_var_placeholder_exceptions(node: Any) -> Any:
    if isinstance(node, list):
        return [strip_env_var_placeholder_exceptions(item) for item in node]

    if not isinstance(node, dict):
        return node

    cleaned = {
        key: strip_env_var_placeholder_exceptions(value)
        for key, value in node.items()
        if key != "$schema"
        # The $schema isn't generated by pydantic, so we drop it
    }

    # Delete the top-level EnvVarPlaceholder definition
    defs = cleaned.get("$defs")
    if isinstance(defs, dict):
        defs.pop("EnvVarPlaceholder", None)

    # For each property, drop the EnvVarPlaceholder branch
    for keyword in ("anyOf", "oneOf"):
        branches = cleaned.get(keyword)
        if not isinstance(branches, list):
            continue

        branches = [
            branch
            for branch in branches
            if "$ref" not in branch or branch["$ref"] != ENV_VAR_PLACEHOLDER_REF
        ]

        if len(branches) == 1:
            return branches[0]

        cleaned[keyword] = branches

    return cleaned


def test_checked_in_schema_matches_generated_model_schema() -> None:
    checked_in_schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))

    assert (
        strip_env_var_placeholder_exceptions(checked_in_schema)
        == Config.model_json_schema()
    )
